Ratelimit by IP address to mitigate reflection attacks
wireapp/coturn pull request #18
Opened 2024-08-07 10:27 UTC by e-lisa

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-08-07 12:29 UTC, z-dule reviewed
LGTM however rate-limiting will be turned off if the size of the table exceeds RATE_LIMIT_TABLE_SIZE (1024).
A suggestion would be to use a linked list instead...

2024-08-07 12:45 UTC, supersven reviewed
Thanks for coming up quickly with a solution. Overall, the code is written very cleanly :+1: 

Please take the time to consider my remarks. Not everything needs to be done; but please think about each of them

2024-08-07 12:45 UTC, supersven commented on examples/run_tests.sh
> +	exit $?
Wrong indentation?

2024-08-07 12:45 UTC, supersven commented on src/server/ns_turn_server.c
> +    for (int i = 0; i < RATE_LIMIT_TABLE_SIZE; i++) {
This lookup seems to be `O(n)` in runtime. I.e. worst case, we're traversing the whole array... I'm wondering if there wouldn't be a more appropriate data structure.

2024-08-07 12:45 UTC, supersven commented on src/server/ns_turn_server.c
> +    for (int i = 0; i < RATE_LIMIT_TABLE_SIZE; i++) {
What if all array elements are occupied? Do we ignore the address then?

2024-08-07 12:45 UTC, supersven commented on src/server/ns_turn_server.c
> +        if (strcmp(rate_limit_table[i].address, address) == 0) {
I'm wondering if it wouldn't be safer to use `strncmp` (or something similar) here?

2024-08-07 12:45 UTC, supersven commented on src/server/ns_turn_server.c
> +        if (strcmp(rate_limit_table[i].address, address) == 0) {
We even got `RATE_LIMIT_IP_ADDRESS_LENGTH`. Can't we use it as max length of the strings to be compared?

2024-08-07 12:45 UTC, supersven commented on src/server/ns_turn_server.c
> +          *colon_pos = '\0';
Sorry, I'm probably blind, but what is the benefit of this statement? I cannot spot where `colon_pos` is used? :thinking:

2024-08-07 12:45 UTC, supersven commented on src/server/ns_turn_server.c
> +      if(!is_address_ratelimit(raddr)) {
Wouldn't it be a bit easier to understand if *all good* returns `0` and error `1`? :thinking: This would also remove the negation.

2024-08-07 12:45 UTC, supersven commented on src/server/ns_turn_session.h
> +#define RATE_LIMIT_WINDOW 60
A mention of the unit would be helpful here: Minutes, Seconds... :smile:

2024-08-07 12:45 UTC, supersven commented on src/server/ns_turn_session.h
> +#define RATE_LIMIT_ENTRY_EXPIRATION_TIME 600
Same here: A unit (in name or comment) would be great. :smile:

2024-08-07 12:45 UTC, supersven commented on src/server/ns_turn_session.h
> +#define RATE_LIMIT_TABLE_SIZE 1024
How did you come up with the table size? (I'm asking to check if the size fits our needs.)

2024-08-07 12:50 UTC, supersven commented
> LGTM however rate-limiting will be turned off if the size of the table exceeds RATE_LIMIT_TABLE_SIZE (1024). A suggestion would be to use a linked list instead...

@z-dule To me the use case (lookup by key) sounds more like a (hash-)map (dictionary). But, I'm not sure if we've got that around. Or, how hard it would be to import.

2024-08-07 13:02 UTC, supersven commented on examples/run_tests.sh
> +grep '401 rate limit exceeded from' /tmp/coturn.log >/dev/null
You asked about tests... A counter-example would probably good as well. I.e. *I'm doing one request less and the message does not show up.*

2024-08-07 13:02 UTC, lwille commented on src/server/ns_turn_server.c
> +          *colon_pos = '\0';
I think this replaces the position of `:` in the string with a zero, thus terminating the string at that position. It's indeed hacky 😅

2024-08-07 13:07 UTC, lwille commented on src/server/ns_turn_server.c
> +      addr_to_string(get_remote_addr_from_ioa_socket(ss->client_socket), raddr);
**thought:** I'd advise against operating on IP addresses as strings. It's not memory-efficient and may lead to all sorts of troubles.
`get_remote_addr_from_ioa_socket` already returns an efficient representation which has separate fields for `address` and `port`, cf. https://man7.org/linux/man-pages/man3/sockaddr.3type.html

2024-08-07 13:07 UTC, supersven commented on src/server/ns_turn_server.c
> +          *colon_pos = '\0';
Ah, I see :bulb:

And, we don't have to care about the now cut off string part, because it's stack allocated.

2024-08-07 13:09 UTC, lwille commented on src/server/ns_turn_server.c
> +          *colon_pos = '\0';
@e-lisa, check out `addr_to_string_no_port` :)

2024-08-07 13:10 UTC, supersven commented on src/server/ns_turn_server.c
> +    for (int i = 0; i < RATE_LIMIT_TABLE_SIZE; i++) {
Hm, I think *my table is full, all requests beyond are fine* won't work here as we're dealing with massive denial of service attacks, no? :thinking:

2024-08-07 13:11 UTC, lwille commented on src/server/ns_turn_server.c
> +        if (strcmp(rate_limit_table[i].address, address) == 0) {
we wouldn't need to care about string comparison issues if we used binary comparison, e.g. `add_eq` from [ns_turn_ioaddr.h](https://github.com/coturn/coturn/blob/master/src/client/ns_turn_ioaddr.h#L69C5-L69C12)

2024-08-07 13:13 UTC, lwille commented on src/server/ns_turn_server.c
> +int is_address_ratelimit(const char *address) {
**suggestion:** use coturn's internal type for address, e.g.

```suggestion
int is_address_ratelimit(const ioa_addr *a) {
```

2024-08-07 13:16 UTC, lwille requested changes

2024-08-07 13:16 UTC, lwille commented on src/server/ns_turn_server.c
> +      char *colon_pos = strchr(raddr, ':');
**issue:** the current implementation will break on IPv6 addresses, which contain multiple colons.

**suggestion:**
Better use the internal type [`ioaddr`](https://github.com/coturn/coturn/blob/master/src/client/ns_turn_ioaddr.h#L44-L48) and the related functions contained in the coturn codebase; it already contains all necessary implementations for IPv6 compatibility.

2024-08-07 13:29 UTC, z-dule commented on src/server/ns_turn_server.c
> +int is_address_ratelimit(const char *address) {
Keep in mind that when the # of elements is small a hash operation can be more expensive than a linear lookup.
If its possible to do a binary compare with the ioaddr type, that would help eliminate the somewhat costly strcmp.
I personally didn't comment more as this in my eyes was meant to be a quick hack to remedy this issue as fast as possible...

2024-08-08 09:00 UTC, e-lisa commented on src/server/ns_turn_server.c
> +    for (int i = 0; i < RATE_LIMIT_TABLE_SIZE; i++) {
Moved from the table to a binary search tree. This approach should be O(log n) for the worst case.

2024-08-08 09:01 UTC, e-lisa commented on src/server/ns_turn_server.c
> +    for (int i = 0; i < RATE_LIMIT_TABLE_SIZE; i++) {
Agreed. New data structure should address this.

2024-08-08 09:02 UTC, e-lisa commented on src/server/ns_turn_server.c
> +        if (strcmp(rate_limit_table[i].address, address) == 0) {
moved to ioa_addr for address comparison and storage in the rate limit tree

2024-08-08 09:08 UTC, e-lisa commented on src/server/ns_turn_server.c
> +      addr_to_string(get_remote_addr_from_ioa_socket(ss->client_socket), raddr);
agreed, moved fully to these provided utilities!

2024-08-08 09:15 UTC, z-dule commented on src/server/ns_turn_server.c
> +
Recursion might be dangerous here, if the table is huge, we will blow up the stack which is usually a page size i.e. 4K...

2024-08-08 09:43 UTC, lwille commented
@e-lisa I updated the Jira issue in the title, as Guillaume created a separate issue for better visibility.

2024-08-08 10:09 UTC, e-lisa commented on src/server/ns_turn_server.c
> +
Unsure about the max size we'll see so i moved both the search and insert over to iteration.

2024-08-08 10:09 UTC, supersven commented on src/server/ns_turn_server.c
> +
Yes :+1: 

And, because it's a tail recursion it can be transformed to e.g.
```c
RateLimitEntry *tmp_root = root;

while(tmp_root != NULL) {
   if(addr_eq_no_port(&tmp_root->address, address)) {
        // we got the right node
        break;
    }
    if (addr_less_eq(address, &root->address)) {
        // go left
        tmp_root = tmp_root->left;
    } else {
        // go right
        tmp_root = tmp_root->root->right;
    }
}

return tmp_root;
```

2024-08-08 10:11 UTC, supersven commented on src/server/ns_turn_server.c
> +
(similar to `rate_limit_insert`)

2024-08-08 10:14 UTC, supersven commented on src/server/ns_turn_server.c
> +void rate_limit_insert(RateLimitEntry **root, ioa_addr *address) {
I think some limit on the size of the data structure would be good. The limit could be big and we could keep track of the size in e.g. a `static` counter.

I'm also wondering if we don't have to care about thread safety? :thinking:

2024-08-08 10:27 UTC, z-dule commented on src/server/ns_turn_server.c
> +void rate_limit_insert(RateLimitEntry **root, ioa_addr *address) {
I know there are a few threading models available, not sure which one we are running in the deployment? @sgodin would be best fit to answer this, but putting a lock around the rate_limit table would hit performance a bit, but might be a good thing to do?

2024-08-08 10:35 UTC, e-lisa commented on src/server/ns_turn_server.c
> +void rate_limit_insert(RateLimitEntry **root, ioa_addr *address) {
If we did set a max size for our structure, what would our behavior be when it is hit? Automatically refuse to send a 401? Send a 401 (feels like that could be exploited). This makes me think we should try to add something to delete items from the tree when they "expire". I am not sure about the best place to put this, but I suspect it might be a level up from this part of the work flow (maybe in the main loop in init main())

Around threads: I think the way it works is that threads are used to handled *established* connections, but this runs in a mono-thread until it is accepted. I could be wrong here, so I will double check.

2024-08-08 10:42 UTC, lwille reviewed
Thank you @e-lisa for implementing these changes! All my concerns were addressed and the btree implementation looks fine as far as I can tell.

2024-08-08 10:42 UTC, lwille approved these changes

2024-08-08 10:45 UTC, lwille commented on src/server/ns_turn_server.c
> +void rate_limit_insert(RateLimitEntry **root, ioa_addr *address) {
I wouldn't put a limit, but having a counter could enable us to do housekeeping e.g. every 1k connections.

How would that work though? Would we just (recursively) walk the tree and delete anything that is expired?

2024-08-08 10:55 UTC, e-lisa commented on src/server/ns_turn_server.c
> +void rate_limit_insert(RateLimitEntry **root, ioa_addr *address) {
I think that would probably be the easiest, and least amount of work. I dont really know how much work our TURN servers do, or how much traffic they are expected to handle as far as new connections.

That said I think just pruning every time we hit 1k addresses should do the trick via traversal.

2024-08-08 11:07 UTC, supersven commented on src/server/ns_turn_server.c
> +void rate_limit_insert(RateLimitEntry **root, ioa_addr *address) {
Yeah, I fear that if this code is run concurrently, it might easily render the data structure into garbage :roll_eyes: 

There are some macros which likely abstract over the threading models:

```c
#define TURN_MUTEX_DECLARE(mutex) turn_mutex mutex;
#define TURN_MUTEX_INIT(mutex) turn_mutex_init(mutex)
#define TURN_MUTEX_INIT_RECURSIVE(mutex) turn_mutex_init_recursive(mutex)
#define TURN_MUTEX_LOCK(mutex) turn_mutex_lock(mutex)
#define TURN_MUTEX_UNLOCK(mutex) turn_mutex_unlock(mutex)
#define TURN_MUTEX_DESTROY(mutex) turn_mutex_destroy(mutex)
```
(https://github.com/wireapp/coturn/blob/wireapp%2F4.6.2-federation/src/server/ns_turn_ioalib.h#L89)

While looking that up (I'm a foreigner in coturn land), I stumbled over [`ns_turn_khash.h`]([ns_turn_khash.h](https://github.com/wireapp/coturn/blob/master/src/server/ns_turn_khash.h)), [`ns_turn_maps.c`](https://github.com/wireapp/coturn/blob/master/src/server/ns_turn_maps.c) and [`ns_turn_maps.h`](https://github.com/wireapp/coturn/blob/master/src/server/ns_turn_maps.h): Looks like we have a fully implemented hash map at our finger tips. Maybe, e.g. `ur_addr_map_*()` and their usages are worth a look?

2024-08-08 11:16 UTC, supersven commented on src/server/ns_turn_server.c
> +void rate_limit_insert(RateLimitEntry **root, ioa_addr *address) {
Ah, sorry, I missed the comment that this will be executed by a single thread (mono threaded) while I wrote the comment above :point_up: .

2024-08-08 11:28 UTC, supersven commented on src/server/ns_turn_server.c
> +void rate_limit_insert(RateLimitEntry **root, ioa_addr *address) {
> I think that would probably be the easiest, and least amount of work. I dont really know how much work our TURN servers do, or how much traffic they are expected to handle as far as new connections.
> 
> That said I think just pruning every time we hit 1k addresses should do the trick via traversal.

I'm wondering if you cannot check and re-balance (in case) on every insert. You're traversing (parts of) the tree then anyways. :thinking: (I would be fine to run out of memory due to too many active users, but not due to garbage :wink: )

2024-08-08 11:40 UTC, supersven commented on src/server/ns_turn_server.c
> +        root->left = rate_limit_delete(root->left, address);
This us still recursive.

2024-08-08 11:41 UTC, supersven commented on src/server/ns_turn_server.c
> +        root->right = rate_limit_delete(root->right, address);
This us still recursive.

2024-08-08 11:42 UTC, supersven commented on src/server/ns_turn_server.c
> +        root->right = rate_limit_delete(root->right, temp->address);
This us still recursive.

2024-08-08 11:45 UTC, supersven commented on src/server/ns_turn_server.c
> +    } else if (addr_less_eq(root->address, address)) {
Isn't this the same condition as in the first `if` statement? :thinking: 

Shouldn't this branch check for *greater than*?

2024-08-08 13:14 UTC, lwille commented on src/server/ns_turn_server.c
> +        root->left = rate_limit_delete(root->left, address);
is recursion really such a big issue here? Stack frames for this function should be rather small (just asking because I'd have trouble coming up with an iterative solution here)

2024-08-08 13:54 UTC, supersven commented on src/server/ns_turn_server.c
> +        root->left = rate_limit_delete(root->left, address);
Hm, I'm not sure how bad it may get in practice. :thinking: I mostly marked these spots because recursion has been replaced on other places as well.

There are examples on the Internet, though:
- https://www.geeksforgeeks.org/binary-search-tree-set-3-iterative-delete/
- glibc's `tdelete()` (though, it's way more sophisticated :exploding_head: ): https://github.com/bminor/glibc/blob/bea2ad022dadae46059de681d902129e56653c85/misc/tsearch.c#L403

We also got no balancing in place for the tree. So, in worst case we end up with linked list characteristics. So, it might be good enough for now; however for upstreaming / future usage we should in my opinion consider to resort to the existing data structure in coturn, the mentioned hash map implementation (`ns_turn_khash.h` and `ns_turn_maps.h`).

2024-08-09 07:56 UTC, supersven commented on src/server/ns_turn_server.c
> +        root->left = rate_limit_delete(root->left, address);
BTW (because I looked that up this morning out of personal interest): The [`tsearch()`](https://man7.org/linux/man-pages/man3/twalk_r.3.html) functions are defined by POSIX and at least part of glibc and musl. Musl is MIT licensed. So, if you decide to not resort to coturn's hash map (for now?), you may want to take a look at the mentioned functions.

2024-08-12 15:48 UTC, sgodin commented on src/server/ns_turn_server.c
> +        root->left = rate_limit_delete(root->left, address);
I think we should be using the coturn hash map (ur_addr_map), it should be optimized already for IP address lookup.

2024-08-12 15:51 UTC, sgodin commented on src/server/ns_turn_server.c
> +void rate_limit_insert(RateLimitEntry **root, ioa_addr *address) {
FYI - there are multiple instances of the ns_turn_server (typically one per thread), since this storage structure is global, it really needs to be protected with locking.

2024-08-12 16:00 UTC, sgodin commented on src/server/ns_turn_server.c
> +void rate_limit_insert(RateLimitEntry **root, ioa_addr *address) {
Some examples can be seen in my federation implementation:  src/apps/relay/federation.c - https://github.com/coturn/coturn/commit/4df39e6533cffe26ae5db3b2ccdd7c4959b17bdf#diff-f3e9f52f2bbc16e4d135ef66e1e6f519ddcce961d24099390951240893d4c60b

2024-08-13 09:55 UTC, e-lisa commented on src/server/ns_turn_server.c
> +        root->left = rate_limit_delete(root->left, address);
in the interest of having **something** to deliver now if we need it, I went ahead and made the binary tree thread safe with the TURN_MUTEX_* functions.

ur_addr_map is probably what we should go with, I can start making the move over to that probably by tomorrow.

2024-08-14 09:25 UTC, z-dule commented on src/server/ns_turn_server.c
> +        if (addr_eq_no_port(&root->address, address)) {
We will likely have a double-lock here, can we run into a dead-lock when parent is waiting for root or vice-versa?

2024-08-14 09:26 UTC, z-dule commented on src/server/ns_turn_server.c
> +        if (addr_eq_no_port(&root->address, address)) {
Maybe easier just to lock the tree? Sure, it will be slighlty less performant, but if as @sgodin says there are multiple instances across threads, a dead-lock is likely to happen...

2024-08-27 14:27 UTC, sgodin commented
It would be ideal if you bumped the version string used by coturn so we can tell the different binaries apart, ie: ones that contain this work and ones that do not.  Check out ns_turn_defs.h:

#define TURN_SERVER_VERSION "wireapp/4.6.2d"

The 4.6.2 part matches the public version this branch is at.  The 'd' is something I added.  You should bump this to be:
#define TURN_SERVER_VERSION "wireapp/4.6.2e"

2024-09-05 09:15 UTC, lwille commented
side note: the PR description is currently just a template; whoever put it there please make sure to fill it with life!

2024-09-09 04:57 UTC, e-lisa commented on src/server/ns_turn_server.c
> +void rate_limit_insert(RateLimitEntry **root, ioa_addr *address) {
This change now uses the `ur_addr_map*` functions. I had to create `*no_port` versions of these functions as outbound ports are randomized, making matching outbound connections between sessions impossible. I wrapped the existing functions to avoid adding additional complexity.

2024-09-09 10:47 UTC, julialongtin approved these changes
looks good to me, but the sleeps in the tests make my skin crawl. approving anyways, because fixing that would be WORK.

2024-09-09 13:56 UTC, supersven commented on src/server/ns_turn_server.c
> +
```suggestion
```

Do we need this blank line? :thinking:

2024-09-09 14:08 UTC, supersven commented on src/server/ns_turn_server.c
> +  int expiration_time = time(NULL) + RATE_LIMIT_ENTRY_EXPIRATION_SECS;
Sorry, but I cannot see where these three variable are read/used. Could you please explain?

2024-09-09 14:15 UTC, supersven commented on src/server/ns_turn_server.c
> +  if (rate_limit_map == 0) {
```suggestion
  if (rate_limit_map == NULL) {
```
While being technically the same, IMHO `NULL` expresses better that we're dealing with a pointer here.

2024-09-09 14:21 UTC, supersven commented on src/server/ns_turn_server.c
> +  ur_addr_map_value_type *ratelimit_ptr = 0;
```suggestion
  ur_addr_map_value_type *ratelimit_ptr = NULL;
```

2024-09-09 14:31 UTC, e-lisa commented on src/server/ns_turn_server.c
> +
no, its gone now :)

2024-09-09 14:31 UTC, e-lisa commented on src/server/ns_turn_server.c
> +  if (rate_limit_map == 0) {
Fair point, NULL is best practices here.

2024-09-09 14:32 UTC, e-lisa commented on src/server/ns_turn_server.c
> +  int expiration_time = time(NULL) + RATE_LIMIT_ENTRY_EXPIRATION_SECS;
An artifact of the binary tree from proof of concept, deleted.

2024-09-09 14:36 UTC, supersven commented on src/server/ns_turn_server.c
> +      rate_limit_entry->expiration_time = current_time + RATE_LIMIT_ENTRY_EXPIRATION_SECS;
I'm wondering if you really need the `expiration_time` field? :thinking: 

Isn't it always `rate_limit_entry->last_request_time + RATE_LIMIT_ENTRY_EXPIRATION_SECS`? Maybe, a small helper function would be sufficient?

2024-09-09 14:39 UTC, supersven commented on src/server/ns_turn_server.c
> +      rate_limit_entry->expiration_time = current_time + RATE_LIMIT_ENTRY_EXPIRATION_SECS;
Is it by intention that `rate_limit_entry->last_request_time` isn't updated here?

2024-09-09 14:46 UTC, supersven commented on src/server/ns_turn_server.c
> +    5TURN_MUTEX_UNLOCK(&rate_limit_main_mutex);
```suggestion
    TURN_MUTEX_UNLOCK(&rate_limit_main_mutex);
```
? :smile_cat:

2024-09-09 15:41 UTC, e-lisa commented on src/server/ns_turn_server.c
> +    5TURN_MUTEX_UNLOCK(&rate_limit_main_mutex);
emacs

2024-09-09 15:41 UTC, supersven commented on src/server/ns_turn_maps.c
> +            free(elem->value);
GCC says:
```
src/server/ns_turn_maps.c: In function ‘addr_list_foreach_del_condition’:
src/server/ns_turn_maps.c:1035:22: warning: passing argument 1 of ‘free’ makes pointer from integer without a cast [-Wint-conversion]
 1035 |             free(elem->value);
      |                  ~~~~^~~~~~~
      |                      |
      |                      ur_addr_map_value_type {aka long unsigned int}
```

2024-09-09 15:42 UTC, supersven commented on src/server/ns_turn_maps.c
> +            count = count++;
```
src/server/ns_turn_maps.c:1038:19: warning: operation on ‘count’ may be undefined [-Wsequence-point]
 1038 |             count = count++;
      |             ~~~~~~^~~~~~~~~
```

2024-09-09 15:43 UTC, supersven commented on src/server/ns_turn_maps.c
> +              free(elem->value);
```
src/server/ns_turn_maps.c:1048:24: warning: passing argument 1 of ‘free’ makes pointer from integer without a cast [-Wint-conversion]
 1048 |               free(elem->value);
      |                    ~~~~^~~~~~~
      |                        |
      |                        ur_addr_map_value_type {aka long unsigned int}
```

2024-09-09 15:43 UTC, supersven commented on src/server/ns_turn_maps.c
> +              count = count++;
```
src/server/ns_turn_maps.c:1051:21: warning: operation on ‘count’ may be undefined [-Wsequence-point]
 1051 |               count = count++;
      |               ~~~~~~^~~~~~~~~
```

2024-09-09 15:44 UTC, supersven commented on src/server/ns_turn_maps.c
> +}
```
src/server/ns_turn_maps.c: In function ‘ur_addr_map_put_no_port’:
src/server/ns_turn_maps.c:889:1: warning: control reaches end of non-void function [-Wreturn-type]
  889 | }
      | ^
```

2024-09-09 15:45 UTC, supersven commented on src/server/ns_turn_maps.c
> +  _ur_addr_map_put(map, key, value, 1);
```
src/server/ns_turn_maps.c: In function ‘ur_addr_map_put’:
src/server/ns_turn_maps.c:893:1: warning: control reaches end of non-void function [-Wreturn-type]
  893 | }
      | ^
```

2024-09-09 15:45 UTC, supersven commented on src/server/ns_turn_maps.c
> +  _ur_addr_map_get(map, key, value, 0);
```
src/server/ns_turn_maps.c: In function ‘ur_addr_map_get_no_port’:
src/server/ns_turn_maps.c:936:1: warning: control reaches end of non-void function [-Wreturn-type]
  936 | }
      | ^
```

2024-09-09 15:46 UTC, supersven commented on src/server/ns_turn_maps.c
> +  _ur_addr_map_get(map, key, value, 1);
```
src/server/ns_turn_maps.c: In function ‘ur_addr_map_get’:
src/server/ns_turn_maps.c:940:1: warning: control reaches end of non-void function [-Wreturn-type]
  940 | }
      | ^
```

2024-09-09 15:52 UTC, supersven commented on src/server/ns_turn_server.c
> +ur_addr_map_cond_func ratelimit_delete_expired(ur_map_value_type value) {
```
src/server/ns_turn_server.c: In function ‘ratelimit_delete_expired’:
src/server/ns_turn_server.c:168:12: warning: returning ‘int’ from a function with return type ‘ur_addr_map_cond_func’ {aka ‘int (*)(long unsigned int)’} makes pointer from integer without a cast [-Wint-conversion]
  168 |     return 1;
      |    
```

2024-09-09 15:53 UTC, supersven commented on src/server/ns_turn_server.c
> +    addr_list_foreach_del_condition(rate_limit_map, ratelimit_delete_expired);
```
src/server/ns_turn_server.c: In function ‘is_address_ratelimit’:
src/server/ns_turn_server.c:187:53: warning: passing argument 2 of ‘addr_list_foreach_del_condition’ from incompatible pointer type [-Wincompatible-pointer-types]
  187 |     addr_list_foreach_del_condition(rate_limit_map, ratelimit_delete_expired);
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                                     |
      |                                                     int (* (*)(ur_map_value_type))(ur_addr_map_value_type) {aka int (* (*)(long unsigned int))(long unsigned int)}
```

2024-09-09 15:54 UTC, supersven commented on src/server/ns_turn_server.c
> +  if (ur_addr_map_get_no_port(rate_limit_map, address, &ratelimit_ptr)) {
```
src/server/ns_turn_server.c:196:47: warning: passing argument 2 of ‘ur_addr_map_get_no_port’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  196 |   if (ur_addr_map_get_no_port(rate_limit_map, address, &ratelimit_ptr)) {
```

2024-09-09 15:55 UTC, supersven commented on src/server/ns_turn_server.c
> +  if (ur_addr_map_get_no_port(rate_limit_map, address, &ratelimit_ptr)) {
```
src/server/ns_turn_server.c:196:56: warning: passing argument 3 of ‘ur_addr_map_get_no_port’ from incompatible pointer type [-Wincompatible-pointer-types]
  196 |   if (ur_addr_map_get_no_port(rate_limit_map, address, &ratelimit_ptr)) {
      |                                                        ^~~~~~~~~~~~~~
      |                                                        |
      |                                                        ur_addr_map_value_type ** {aka long unsigned int **}
```

2024-09-09 15:59 UTC, supersven commented on src/server/ns_turn_server.c
> +  int expiration_time = current_time + RATE_LIMIT_ENTRY_EXPIRATION_SECS;
```
src/server/ns_turn_server.c:191:7: warning: unused variable ‘expiration_time’ [-Wunused-variable]
  191 |   int expiration_time = current_time + RATE_LIMIT_ENTRY_EXPIRATION_SECS;
      |       ^~~~~~~~~~~~~~~
```

2024-09-09 18:42 UTC, e-lisa commented on src/server/ns_turn_server.c
> +      rate_limit_entry->expiration_time = current_time + RATE_LIMIT_ENTRY_EXPIRATION_SECS;
expiration time has been removed/deleted

2024-09-09 19:52 UTC, e-lisa commented on src/server/ns_turn_server.c
> +      rate_limit_entry->expiration_time = current_time + RATE_LIMIT_ENTRY_EXPIRATION_SECS;
It was by intention but after spending time thinking about it, I believe we should keep extending the window. We should have RATE_LIMIT_WINDOW_SECS fully expire before we reset the count.

This means the WINDOW extends every time a new 401 Unauthorized hits Coturn, which IMHO is more inline with what this rate limiting code should be doing.

2024-09-10 08:33 UTC, supersven commented on src/server/ns_turn_ratelimit.c
> +  if (rateLimitEntry->last_request_time + RATE_LIMIT_MAX_REQUESTS_PER_WINDOW < current_time)
Is this calculation correct? Shouldn't it be

```suggestion
  if (rateLimitEntry->last_request_time + RATE_LIMIT_WINDOW_SECS < current_time)
```
:thinking:

2024-09-10 14:31 UTC, e-lisa commented on src/server/ns_turn_ratelimit.c
> +  if (rateLimitEntry->last_request_time + RATE_LIMIT_MAX_REQUESTS_PER_WINDOW < current_time)
Correct!

2024-09-10 14:37 UTC, supersven approved these changes
Thanks a lot for "going the extra mile" :+1:

2024-09-12 16:31 UTC, merged

2024-09-17 13:34 UTC, sgodin commented on src/server/ns_turn_maps.c
Sorry I'm late to the game here.  You don't need to change this, but I just wanted to point out there has been a shift in the public repo to favor using bool over int for boolean parameters and variables.

2024-09-17 13:44 UTC, sgodin commented on src/server/ns_turn_maps.h
>  typedef struct _ur_addr_map ur_addr_map;
I hate to say this so late in the game, but couldn't you have just stored all your addresses with a port set to 0, and then in your lookup method, make sure you 0 out the port of the address you are comparing?  That way you could just use the built in ur_addr_map un modified?

2024-09-17 13:49 UTC, sgodin commented
> It would be ideal if you bumped the version string used by coturn so we can tell the different binaries apart, ie: ones that contain this work and ones that do not. Check out ns_turn_defs.h:
> 
> #define TURN_SERVER_VERSION "wireapp/4.6.2d"
> 
> The 4.6.2 part matches the public version this branch is at. The 'd' is something I added. You should bump this to be: #define TURN_SERVER_VERSION "wireapp/4.6.2e"

Don't think this was done in the PR....

2024-09-17 17:30 UTC, e-lisa commented
> > It would be ideal if you bumped the version string used by coturn so we can tell the different binaries apart, ie: ones that contain this work and ones that do not. Check out ns_turn_defs.h:
> > #define TURN_SERVER_VERSION "wireapp/4.6.2d"
> > The 4.6.2 part matches the public version this branch is at. The 'd' is something I added. You should bump this to be: #define TURN_SERVER_VERSION "wireapp/4.6.2e"
> 
> Don't think this was done in the PR....

I think it might have been reverted by mistake when squashing. I have created a new PR to address this: https://github.com/wireapp/coturn/pull/22