Add container with pre-stop hook script.
wireapp/coturn pull request #5
Opened 2022-06-07 14:57 UTC by sysvinit

We need to be able to detect traffic drain conditions when performing graceful restarts of coturn. This change adds a container image definition which derives from another Debian-based coturn image, and adds a script to the image which polls the metrics endpoint until the number of active allocations reaches zero.

TODO(sysvinit): test this image works correctly as a replacement for existing usages of our coturn image.

2022-06-07 15:17 UTC, supersven requested changes

2022-06-07 15:17 UTC, supersven commented on docker/coturn/wireapp/pre-stop-hook.sh
> +#!/bin/sh
I'm wondering if it wouldn't be good to add some log output (`echo`) to this script. If it fails, it's a black box and hard to analyze. :thinking:

2022-06-07 15:17 UTC, supersven commented on docker/coturn/wireapp/Dockerfile
> +USER nobody:nogroup
No `ENTRY_POINT` / `CMD` needed?

2022-06-07 15:17 UTC, supersven commented on docker/coturn/wireapp/Dockerfile
> +ARG coturn_image=coturn/coturn
So explanation describing this image would be good. Probably, this will be similar to the description of this PR.

2022-06-08 10:57 UTC, sysvinit commented on docker/coturn/wireapp/pre-stop-hook.sh
> +#!/bin/sh
Fixed in [237ebac](https://github.com/wireapp/coturn/pull/5/commits/237ebac139a3b37b5589edae4f3196847c217d2f)?

2022-06-08 10:57 UTC, sysvinit commented on docker/coturn/wireapp/Dockerfile
> +USER nobody:nogroup
No, this is inherited from the base image. (This can be verified by building the image and then `docker inspect`ing the result to check the metadata.)

2022-06-08 10:57 UTC, sysvinit commented on docker/coturn/wireapp/Dockerfile
> +ARG coturn_image=coturn/coturn
Fixed in [9e4b47a](https://github.com/wireapp/coturn/pull/5/commits/9e4b47ac86f1250b7985288c0e3791c9cd6a7749)?

2022-06-08 11:15 UTC, supersven approved these changes
All comments solved.

2022-06-08 11:15 UTC, supersven commented on docker/coturn/wireapp/Dockerfile
> +ARG coturn_image=coturn/coturn
Yep, :+1:

2022-06-08 14:30 UTC, merged