Reintroduce username labels in metrics and make them configurable.
wireapp/coturn pull request #7
Opened 2022-06-15 12:17 UTC by sysvinit

This is the internal half of https://wearezeta.atlassian.net/browse/SQPIT-1012. Once we have this tested and merged, I intend to rebase this fix and send it upstream.

This change reintroduces the username metrics previously removed in #4, and adds a configuration gate to disable them at runtime if required.

2022-06-16 07:39 UTC, supersven requested changes

2022-06-16 07:39 UTC, supersven commented on src/apps/relay/prom_server.c
> +    const char *label[] = {realm, 0};
Same question about `0` vs. `NULL` here :smile_cat:

2022-06-16 07:39 UTC, supersven commented on src/apps/relay/mainrelay.h
> +  int  prometheus_username_labels;
As the `prometheus` flag is represented by a full `int`, I'm wondering if we shouldn't encode this additional information (*show username labels*) there? :thinking: 

Might be over optimization...

2022-06-16 11:51 UTC, sysvinit commented on src/apps/relay/mainrelay.h
> +  int  prometheus_username_labels;
I think my main objection here is that adding bitmask flags is a small increase in complexity on the code which reads the flags. Principle of least astonishment applies here, I think.

2022-06-16 11:54 UTC, sysvinit commented on src/apps/relay/prom_server.c
> +    const char *label[] = {realm, 0};
I couldn't tell you why I used `0` there instead of `NULL`. Maybe it's too much C programmer brain and time spent thinking about vaguely pointer-integer shaped objects.

2022-06-16 11:55 UTC, sysvinit commented on src/apps/relay/prom_server.c
> +    const char *label[] = {realm, 0};
Fixed in [51c6f86](https://github.com/wireapp/coturn/pull/7/commits/51c6f865d48cea4aafb063dfe6b03fcf9c3f1e1a).

2022-06-20 07:04 UTC, supersven approved these changes
LGTM :+1:

2022-06-20 07:04 UTC, supersven commented on src/apps/relay/mainrelay.h
> +  int  prometheus_username_labels;
Well, if that's how things are done in `coturn`, I'm fine with it. :smile_cat:

2022-06-20 13:33 UTC, merged